// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "fs";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Mirrors Next.js's env precedence: .env.local (real values, gitignored,
// created by `vercel env pull`) wins over .env (committed placeholders).
config({ path: existsSync(".env.local") ? ".env.local" : ".env", quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
